apiVersion: v1
kind: Service
metadata:
  name: techtrends             
  namespace: sandbox
spec:
  selector:
    app: techtrends            
  externalIPs:
    - 10.42.0.11
  ports:
    - protocol: {{ .Values.service.protocol }} 
      port: {{ .Values.service.port }}                  
      targetPort: {{ .Values.service.targetport }}            
  type: {{ .Values.service.clusterIp }}
