apiVersion: v1     
name: techtrends	 		             // name for our chart in this case techtrends
description: techtrends project 	 // description to that helm chart 
keywords:  				                 // keywords for quick identification of what the chart does 
- techtrends
version: 1.0.0  			             // we have the version 
maintainers: 				               // here names of who did it 
- name: ahmedalassafy
  email: ahmedalassafy@xyz.com 
