namespace:
  name: staging    
 
replicaCount: 3       

service: 
  port: 5111              
       
resources:
  requests: 
    memory: "90Mi"    
    cpu: "300m"   
  limits:
    memeory: "128Mi"   
    cpu: "500m"   

